### ISSUE TITLE
Phase 2 Site Testing and QA Checklist

### ISSUE THREAD

**Issue by unicornfancy** [unicornfancy/Automattic-Trial#18]
Confirm the following are true: 

Basics
- [ ] Site is fully responsive on phone, tablet, and desktop
- [ ] Site works properly in all browsers as defined [here](https://make.wordpress.org/core/handbook/best-practices/browser-support/) 
- [ ] Images are HiDPI and optimized for retina displays
- [ ] Jetpack is installed and connected
- [ ] Credit link exists

Theme & Site Setup
- [ ] Theme runs without errors or warnings
- [ ] 404 page exists and looks correct
- [ ] Archive looks correct
- [ ] Search results page looks correct
- [ ] Redirects are in place from former site
- [ ] Theme & Plugin files are organized and documented
- [ ] Theme tested with Gutenberg unit test data

Accessibility 
- [ ] Meets [Accessibility Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/accessibility-coding-standards/) 
- [ ] Load time is reasonable
- [ ] Site does well in WebPageTest.org and/or Lighthouse tests for mobile and desktop
- [ ] Contrast is adequate
- [ ] Font size and spacing is easy to read
- [ ] Links are consistent with labels that make sense (no "click here")
- [ ] Logo/site name is prominent
- [ ] Navigation is easily identifiable
- [ ] Navigation labels are clear, concise and consistent across the site
- [ ] Number of buttons/links on a given page or section is reasonable
- [ ] Site search is easy to find and access
- [ ] Styles and colors are consistent
- [ ] URLs are meaningful and user-friendly
- [ ] Images have appropriate ALT tags
- [ ] Home page is digestible in 5 seconds or less
- [ ] Previews on social sharing services look reasonable

Security
- [ ] Site is ready for SSL-only usage without any mixed content warnings
- [ ] Users can only access the parts of sites they are supposed to access
- [ ] [Security best practices are in use](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) 

Data and Form Handling
- [ ] Null input is handled reasonably
- [ ] Unexpected input and special characters are handled reasonably
- [ ] Using the quoting character, ( ‘ ) does not cause an error
- [ ] The data always have integrity
- [ ] Data input and output sanitized and validated appropriately
- [ ] All the math adds up
- [ ] Field size limits reasonable
- [ ] Data values at boundaries do not cause problems
- [ ] If the form is integrated with a third-party service or platform,  all instances of it been tested (e.g. widget, footer, /subscribe page). It works as expected for the frontend user and admin. (e.g. a MailChimp subscriber form).
